# Supported funding model platforms

github: filips123
tidelift: npm/zeroframe-ws-client

open_collective: filips123
patreon: filips
ko_fi: filips
liberapay: filips

custom: ['https://donorbox.org/filips', 'https://buymeacoff.ee/filips', 'https://beerpay.io/filips123', 'https://tippin.me/@123filips123']
